package mainWindows;
import classes.misc.*;
import classes.entities.*;
import classes.runnables.Dystrybutor;
import classes.runnables.ExtThread;
import classes.runnables.Klient;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * 
 * @author Mateusz Ksok
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() 
    {
        super("Flixnet GO");
        initComponents();
        symulacja = new Symulacja();
    }
    
    private void resetSimulation()
    {
        symulacja.setFinish(true);
        symulacja = new Symulacja();
            
        clientList.setModel(new DefaultListModel());
        distribList.setModel(new DefaultListModel());
        productList.setModel(new DefaultListModel());
        
        Subscription.setBasicPrice(19.99f);
        Subscription.setFamilyPrice(29.99f);
        Subscription.setPremiumPrice(35.99f);
        
        basicSubTextField.setText(Double.toString(
                Math.round(Subscription.getBasicPrice() * 100.0) / 100.0));
        familySubTextField.setText(Double.toString(
                Math.round(Subscription.getFamilyPrice() * 100.0) / 100.0));
        premiumSubTextField.setText(Double.toString(
                Math.round(Subscription.getPremiumPrice() * 100.0) / 100.0));
        
        symulacja.setPaused(true);
        symulacja.start();
            
        playPauseButton.setText("Start");
        
    }
    
    
    private void updateGUI()
    {
        if (this.symulacja.isFinish())
            resetSimulation();
        /*
            Odświeżanie wskazania daty i salda:
        */
        double a = symulacja.getFlixnet().getSaldo();
        double x = Math.round(a * 100.0) / 100.0;
        saldoLabel.setText("Saldo: " + Double.toString(x));
        timeLabel.setText(
                "Data: " +
                new SimpleDateFormat("dd.MM.yyyy").format(
                symulacja.getObecnaData().getTime())
                );
        
        /*
        Update listy produktów: przeiteruj przez całą listę i dodaj wszystkie, które
        się powtarzają
        */
        for (int i = 0; i < symulacja.getListaProduktow().size(); i++)
        {
            // Jeśli model nie zawiera danego produktu z listy
            if (!((DefaultListModel)productList.getModel()).
                    contains(symulacja.getListaProduktow().get(i)))
            {   // to go dodaj do niego.
                ((DefaultListModel)productList.getModel()).addElement
                                (symulacja.getListaProduktow().get(i));
            }
        }
        // Drugi etap: stwórz listę indeksów elementów, które zawiera model listy
        // a których nie zawierają właściwe dane. Potrzebujemy wykonywać ten krokjedynie
        // dla produktów, ponieważ jedynie one mogą być usunięte w sytuacji innej niż
        // na przycisk.
        
        LinkedList<Product> toDelete = new LinkedList();
        DefaultListModel<Product> dlmProd = (DefaultListModel)productList.getModel();
        for (int i = 0; i < productList.getModel().getSize(); i++)
        {
            if (!symulacja.getListaProduktow().contains(dlmProd.get(i)))
                toDelete.add(dlmProd.get(i));
        }
        
        for (Product i : toDelete)
        {
            dlmProd.removeElement(i);
        }
        
        /*
         * Update listy klientów:
         */
        for (int i = 0; i < symulacja.getListaKlientow().size(); i++)
        {
            // Jeśli model nie zawiera danego klientu z listy
            if (!((DefaultListModel)clientList.getModel()).
                    contains(symulacja.getListaKlientow().get(i)))
            {   // to go dodaj do niego.
                ((DefaultListModel)clientList.getModel()).addElement
                                (symulacja.getListaKlientow().get(i));
            }
        }
        
        /*
         * Update listy dystrybutorów
         */
        for (int i = 0; i < symulacja.getListaDystrybutorow().size(); i++)
        {
            // Jeśli model nie zawiera danego klientu z listy
            if (!((DefaultListModel)distribList.getModel()).
                    contains(symulacja.getListaDystrybutorow().get(i)))
            {   // to go dodaj do niego.
                ((DefaultListModel)distribList.getModel()).addElement
                                (symulacja.getListaDystrybutorow().get(i));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterGroup = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        newKlient = new javax.swing.JButton();
        newDistrib = new javax.swing.JButton();
        newProduct = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        delProduct = new javax.swing.JButton();
        delDistrib = new javax.swing.JButton();
        delClient = new javax.swing.JButton();
        filterField = new javax.swing.JTextField();
        actRadioBtn = new javax.swing.JRadioButton();
        nameRadioBtn = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        playPauseButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        distribList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientList = new javax.swing.JList<>();
        tab2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        basicSubTextField = new javax.swing.JTextField();
        familySubTextField = new javax.swing.JTextField();
        premiumSubTextField = new javax.swing.JTextField();
        basicSubBtn = new javax.swing.JButton();
        familySubBtn = new javax.swing.JButton();
        premiumSubBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        newKlient.setText("Dodaj klienta");
        newKlient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newKlientActionPerformed(evt);
            }
        });

        newDistrib.setText("Dodaj dystrybutora");
        newDistrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDistribActionPerformed(evt);
            }
        });

        newProduct.setText("Dodaj losowy produkt");
        newProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductActionPerformed(evt);
            }
        });

        timeLabel.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N

        saldoLabel.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N

        delProduct.setText("Usuń wybrane");
        delProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delProductActionPerformed(evt);
            }
        });

        delDistrib.setText("Usuń dystrybutora");
        delDistrib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDistribActionPerformed(evt);
            }
        });

        delClient.setText("Usuń klienta");
        delClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delClientActionPerformed(evt);
            }
        });

        filterGroup.add(actRadioBtn);
        actRadioBtn.setText("Aktorzy");

        filterGroup.add(nameRadioBtn);
        nameRadioBtn.setSelected(true);
        nameRadioBtn.setText("Nazwa");

        jButton2.setText("Wyszukaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ikonkaDoProjektu.jpg"))); // NOI18N

        playPauseButton.setText("Wstrzymaj");
        playPauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nameRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(actRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filterField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newDistrib, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(delDistrib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newKlient, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(delClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playPauseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saldoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDistrib)
                    .addComponent(newProduct)
                    .addComponent(newKlient)
                    .addComponent(filterField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delDistrib)
                    .addComponent(delClient)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actRadioBtn)
                    .addComponent(nameRadioBtn)
                    .addComponent(playPauseButton))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel1.setText("Lista produktów:");

        jLabel2.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel2.setText("Lista dystrybutorów:");
        jLabel2.setMaximumSize(new java.awt.Dimension(41, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(41, 17));
        jLabel2.setPreferredSize(new java.awt.Dimension(41, 17));

        jLabel3.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        jLabel3.setText("Lista klientów:");
        jLabel3.setMaximumSize(new java.awt.Dimension(82, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(82, 17));
        jLabel3.setPreferredSize(new java.awt.Dimension(82, 17));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        productList.setToolTipText("");
        productList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productList);

        distribList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distribListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(distribList);

        clientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(clientList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                    .addContainerGap(361, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)))
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(533, Short.MAX_VALUE)))
            .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Symulacja", tab1);

        jLabel4.setText("Obecna cena abonamentu Premium:");

        jLabel5.setText("Obecna cena abonamentu Basic:");

        jLabel6.setText("Obecna cena abonamentu Family:");

        basicSubBtn.setText("Zmień...");
        basicSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicSubBtnActionPerformed(evt);
            }
        });

        familySubBtn.setText("Zmień...");
        familySubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familySubBtnActionPerformed(evt);
            }
        });

        premiumSubBtn.setText("Zmień...");
        premiumSubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiumSubBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Zresetuj symulację");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sherkx2.png"))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("© Copyright Gibson Corp, 2019 Nashville, Tennessee, USA.");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(basicSubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basicSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(premiumSubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(premiumSubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tab2Layout.createSequentialGroup()
                                .addComponent(familySubTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(familySubBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tab2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicSubTextField)
                    .addComponent(basicSubBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familySubTextField)
                    .addComponent(familySubBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(premiumSubTextField)
                    .addComponent(premiumSubBtn))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(121, 121, 121)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jTabbedPane2.addTab("Ustawienia", tab2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newDistribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDistribActionPerformed
        symulacja.newDystrybutor();
        updateGUI();
    }//GEN-LAST:event_newDistribActionPerformed

    private void newKlientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newKlientActionPerformed
        symulacja.newKlient(); 
        updateGUI();
    }//GEN-LAST:event_newKlientActionPerformed

    private void newProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductActionPerformed
        symulacja.newProduct();
        updateGUI();
    }//GEN-LAST:event_newProductActionPerformed

    private void delDistribActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDistribActionPerformed
        DefaultListModel model = (DefaultListModel)distribList.getModel();
        /*
        Usuwanie produktów dystrybutora, który został wybrany do usunięcia
        */
        LinkedList<Product> toDelete = new LinkedList();
        if (distribList.getSelectedValue() != null)
        {
            for (Product i : symulacja.getListaProduktow())
            {

                /*
                 *  Jeśli dystrybutorem danego produktu jest dystrybutor przeznaczony do
                 *  usunięcia, to dodaj go do listy produktów do usunięcia.
                 */
                if (i.getDystr() == distribList.getSelectedValue().getByt())
                {
                    toDelete.add(i);
                }
            }

            DefaultListModel productModel = (DefaultListModel)productList.getModel();
            for (Product i : toDelete)
            {
                productModel.removeElement(i);
            }

            symulacja.getListaProduktow().removeAll(toDelete);

            distribList.getSelectedValue().setCzySkonczyc(true);
            symulacja.getListaDystrybutorow().remove(distribList.getSelectedValue());
            model.removeElement(distribList.getSelectedValue());
        }
    }//GEN-LAST:event_delDistribActionPerformed

    private void delClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delClientActionPerformed
        DefaultListModel model = (DefaultListModel)clientList.getModel();
        clientList.getSelectedValue().setCzySkonczyc(true);
        symulacja.getListaKlientow().remove(clientList.getSelectedValue());
        model.removeElement(clientList.getSelectedValue());
        updateGUI();
    }//GEN-LAST:event_delClientActionPerformed

    private void productListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productListMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) 
        {
            int index = list.locationToIndex(evt.getPoint());
            DefaultListModel model = (DefaultListModel)productList.getModel();
            Product prod = (Product)model.get(index);
            
            PopupWindow p = new PopupWindow(prod);
            p.setVisible(true);
        }
    }//GEN-LAST:event_productListMouseClicked

    private void distribListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distribListMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) 
        {
            int index = list.locationToIndex(evt.getPoint());
            DefaultListModel model = (DefaultListModel)distribList.getModel();
            Dystrybutor distr = (Dystrybutor)((ExtThread)model.get(index)).getByt();
            
            InfoWindow wnd = new InfoWindow(distr);
            wnd.setVisible(true);
        }
    }//GEN-LAST:event_distribListMouseClicked

    private void basicSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicSubBtnActionPerformed
        try
        {
            double cena = Math.round(Double.parseDouble(basicSubTextField.getText())*100) / 100;
            if (cena <= 0)
                throw new NumberFormatException();
            Subscription.setBasicPrice(cena);
            
            for (ExtThread klient : symulacja.getListaKlientow())
            {
                Klient kl = (Klient)klient.getByt();
                if (kl.getSub().getType().equals("Basic"))
                   kl.getSub().setPrice(cena);
            }
        }
        catch(NumberFormatException e)
        {    
            System.out.println("Podano złą wartość. Podana liczba musi być większa od zera.");
        }
    }//GEN-LAST:event_basicSubBtnActionPerformed

    private void familySubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familySubBtnActionPerformed
        try
        {
            double price = Math.round(Double.parseDouble(familySubTextField.getText())*100) / 100;
            if (price <= 0) 
                throw new NumberFormatException();
            Subscription.setFamilyPrice(price);
            for (ExtThread klient : symulacja.getListaKlientow())
            {
                Klient kl = (Klient)klient.getByt();
                if (kl.getSub().getType().equals("Family"))
                   kl.getSub().setPrice(price);
            }
        }
        catch(NumberFormatException e)
        {    
            System.out.println("Podano złą wartość. Liczba musi być większa od zera.");
        }
    }//GEN-LAST:event_familySubBtnActionPerformed

    private void premiumSubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiumSubBtnActionPerformed
        try
        {
            double price = Math.round(Double.parseDouble(premiumSubTextField.getText())*100) / 100;
            if (price <= 0) 
                throw new NumberFormatException();
            Subscription.setPremiumPrice(price);
            
            for (ExtThread klient : symulacja.getListaKlientow())
            {
                Klient kl = (Klient)klient.getByt();
                if (kl.getSub().getType().equals("Premium"))
                   kl.getSub().setPrice(price);
            }
        }
        catch(NumberFormatException e)
        {    
            System.out.println("Podano złą wartość. Liczba musi być większa od zera.");
        }
    }//GEN-LAST:event_premiumSubBtnActionPerformed

    private void clientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientListMouseClicked
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) 
        {
            int index = list.locationToIndex(evt.getPoint());
            DefaultListModel model = (DefaultListModel)clientList.getModel();
            Klient klient = (Klient)((ExtThread)model.get(index)).getByt();
            
            InfoWindow wnd = new InfoWindow(klient);
            wnd.setVisible(true);
        }
    }//GEN-LAST:event_clientListMouseClicked

    private void delProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delProductActionPerformed
        DefaultListModel model = (DefaultListModel)productList.getModel();
        symulacja.getListaProduktow().remove(productList.getSelectedValue());
        model.removeElement(productList.getSelectedValue());
        updateGUI();
    }//GEN-LAST:event_delProductActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultListModel<Product> dlm = new DefaultListModel();
        String str = filterField.getText();
        if (!str.equals(""))
        {
            for (Product i: symulacja.getListaProduktow())
            {
                if (nameRadioBtn.isSelected())
                {
                    if (i.toString().contains(str))
                    {
                        dlm.addElement(i);
                    }
                }

                else if (actRadioBtn.isSelected())
                {
                    if (i instanceof Film)
                    {
                        for (String s : ((Film) i).getListaAktorow())
                        {
                            if (s.contains(str))
                            {
                                dlm.addElement(i);
                                break;
                            }
                        }
                    }

                    else if (i instanceof Serial)
                    {
                        for (String s : ((Serial) i).getListaAktorow())
                        {
                            if (s.contains(str))
                            {
                                dlm.addElement(i);
                                break;
                            }
                        }
                    }
                }
            }
            
            FilterWindow wnd = new FilterWindow(dlm);
            wnd.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void playPauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPauseButtonActionPerformed
        if (symulacja.isPaused())
            playPauseButton.setText("Wstrzymaj");
        
        else playPauseButton.setText("Wznów");
        symulacja.setPaused(!symulacja.isPaused());
    }//GEN-LAST:event_playPauseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Jesteś pewien?", "PRZYPAŁ",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            resetSimulation();
        } else {
            //nic się nie dzieje
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Okno o = new Okno();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            o.setVisible(true);
        });
        
        o.productList.setModel(new DefaultListModel());
        o.distribList.setModel(new DefaultListModel());
        o.clientList.setModel(new DefaultListModel());
        
        o.basicSubTextField.setText(Double.toString(
                Math.round(Subscription.getBasicPrice() * 100.0) / 100.0));
        
        o.familySubTextField.setText(Double.toString(
                Math.round(Subscription.getFamilyPrice() * 100.0) / 100.0));
        
        o.premiumSubTextField.setText(Double.toString(
                Math.round(Subscription.getPremiumPrice() * 100.0) / 100.0));
        
        o.symulacja.start();
        
        for (;;)
        {
            o.updateGUI();
            try {
                Thread.sleep(100);              
            } catch (InterruptedException ex) {
                Logger.getLogger("Thread odpowiedzialny za aktualizację GUI się przewrócił");
            }
        }
    }

    
    private Symulacja symulacja;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton actRadioBtn;
    private javax.swing.JButton basicSubBtn;
    private javax.swing.JTextField basicSubTextField;
    private javax.swing.JList<ExtThread> clientList;
    private javax.swing.JButton delClient;
    private javax.swing.JButton delDistrib;
    private javax.swing.JButton delProduct;
    private javax.swing.JList<ExtThread> distribList;
    private javax.swing.JButton familySubBtn;
    private javax.swing.JTextField familySubTextField;
    private javax.swing.JTextField filterField;
    private javax.swing.ButtonGroup filterGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton nameRadioBtn;
    private javax.swing.JButton newDistrib;
    private javax.swing.JButton newKlient;
    private javax.swing.JButton newProduct;
    private javax.swing.JButton playPauseButton;
    private javax.swing.JButton premiumSubBtn;
    private javax.swing.JTextField premiumSubTextField;
    private javax.swing.JList<Product> productList;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
